### ISSUE TITLE
未能实现效果图

### ISSUE THREAD

**Issue by adminDzl** [ren5927/CesiumDarkMap#1]
我使用的cesium版本是1.89/1.91版本，没有如下图效果，是不是存在版本适配问题？
（没有此图效果）:https://github.com/ren5927/CesiumDarkMap/blob/main/demo.png

**Comment by ren5927** [comment]
![1697511240914](https://github.com/ren5927/CesiumDarkMap/assets/51333586/3e7971bd-db7d-4586-b79c-f61774689641)
1.91截图,注意使用方法,以及,你选择的底图是不是0,我这里只加了一个,所以get(0)
